/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.consultas;

import dto.CompanyaAerea;

import java.util.HashMap;
import javax.swing.JPanel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import ui.panelAyuda;

import static utils.CSV.BorrarLineasCSV.borrarLineaCSV;
import static utils.CSV.CrearCSV.writeCompanyaCSV;
import static utils.CSV.ModificarCSV.modificarLineaCSV;
import static utils.Archivos.PATH_COMPANYAAEREA;

/**
 *
 * @author laura
 */
public class GestionCompanyas extends javax.swing.JFrame {

    private HashMap<String, CompanyaAerea> companyaMap = new HashMap<>();
    private panelAyuda ayudaFrame = new panelAyuda();
    /**
     * Creates new form GestionCompanyas
     */
    
    public GestionCompanyas() {
        initComponents();
        // PARA EL F1
              // Configurar el KeyListener para detectar la tecla F1
        addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                // No necesitas implementar esto para la tecla F1
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_F1) {
                    // Mostrar el JPanel en una nueva ventana al presionar F1
                    mostrarPanelEnVentana(ayudaFrame, "Ayuda");
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // No necesitas implementar esto para la tecla F1
            }
        });

        // Hacer que el JFrame sea enfocable para que pueda recibir eventos de teclado
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrefijoComp = new javax.swing.JTextField();
        txtCodigoComp = new javax.swing.JTextField();
        txtNombreComp = new javax.swing.JTextField();
        txtDirSedeCentral = new javax.swing.JTextField();
        txtMunicipioSedeCentral = new javax.swing.JTextField();
        txtTlfInfoPasajeros = new javax.swing.JTextField();
        txtTlfInfoAeropuerto = new javax.swing.JTextField();
        btnGuardarComp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de las Compañías Aéreas");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Prefijo:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nombre Compañía:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Dirección Sede Central:");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Municipio Sede Central:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Teléfono info. pasajeros:");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Teléfono info. aeropuertos:");

        txtPrefijoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoCompActionPerformed(evt);
            }
        });

        btnGuardarComp.setText("Guardar");
        btnGuardarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ayuda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(22, 22, 22)
                                .addComponent(jButton1)
                                .addGap(21, 21, 21)
                                .addComponent(btnGuardarComp))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTlfInfoAeropuerto)
                                .addComponent(txtTlfInfoPasajeros)
                                .addComponent(txtMunicipioSedeCentral)
                                .addComponent(txtDirSedeCentral)
                                .addComponent(txtNombreComp)
                                .addComponent(txtCodigoComp)
                                .addComponent(txtPrefijoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefijoComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirSedeCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunicipioSedeCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlfInfoPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlfInfoAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarComp)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrefijoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoCompActionPerformed
    private HashMap<String, CompanyaAerea> obtenerHashMapActual() {
        // Devolver el HashMap almacenado en tu formulario
        return companyaMap;
    }
    private void btnGuardarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompActionPerformed
        CompanyaAerea cAerea = new CompanyaAerea();
//ESTO FUNCIONA. HAY QUE IMPLEMENTAR VALIDACIONES.
        cAerea.setPrefijo(Integer.parseInt(txtPrefijoComp.getText()));
        cAerea.setCodigo(txtCodigoComp.getText());
        cAerea.setNombre(txtNombreComp.getText());
        cAerea.setDireccion(txtDirSedeCentral.getText());
        cAerea.setNumInfoAeropuerto(txtTlfInfoPasajeros.getText());
        cAerea.setNumInfoPasajero(txtTlfInfoAeropuerto.getText());
        cAerea.setMunicipio(txtMunicipioSedeCentral.getText());
        // Obtener el HashMap actual de CompanyaAerea
        HashMap<String, CompanyaAerea> mapaCompanya = obtenerHashMapActual();

        // Agregar la nueva instancia al HashMap
        mapaCompanya.put(cAerea.getCodigo(), cAerea);

        // Llamar al método para escribir en el archivo CSV
        writeCompanyaCSV(PATH_COMPANYAAEREA, mapaCompanya);
        System.out.println(cAerea.getNombre() + " " + cAerea.getCodigo() + " " + cAerea.getDireccion());
        //vaciado del codigo si ha ido bien
        txtPrefijoComp.setText("");
        txtCodigoComp.setText("");
        txtNombreComp.setText("");
        txtDirSedeCentral.setText("");
        txtTlfInfoPasajeros.setText("");
        txtTlfInfoAeropuerto.setText("");
        txtMunicipioSedeCentral.setText("");

    }//GEN-LAST:event_btnGuardarCompActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigoABorrar = txtPrefijoComp.getText(); // Reemplaza con el código de la compañía que deseas borrar
        borrarLineaCSV(PATH_COMPANYAAEREA, codigoABorrar);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigoAModificar = txtCodigoComp.getText(); // Reemplaza con el código de la compañía que deseas modificar
        String nuevoPrefijo = txtPrefijoComp.getText();
        String nuevoNombre = txtNombreComp.getText();
        String nuevaDireccion = txtDirSedeCentral.getText();
        String nuevoMunicipio = txtMunicipioSedeCentral.getText();
        String nuevoNumInfoPasajero = txtTlfInfoPasajeros.getText();
        String nuevoNumInfoAeropuerto = txtTlfInfoAeropuerto.getText();

        // Construir la línea actualizada para el CSV
        String nuevaLinea = String.format("%s;%s;%s;%s;%s;%s;%s",
                nuevoPrefijo, codigoAModificar, nuevoNombre, nuevaDireccion,
                nuevoMunicipio, nuevoNumInfoPasajero, nuevoNumInfoAeropuerto);

        // Llamar al método para modificar la línea en el archivo CSV
        modificarLineaCSV(PATH_COMPANYAAEREA, codigoAModificar, nuevaLinea);
        System.out.println(nuevaLinea);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Cerrar el formulario actual
                dispose();

              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
     mostrarPanelEnVentana(ayudaFrame, "Ayuda");
              
    }//GEN-LAST:event_jButton4ActionPerformed
  private void mostrarPanelEnVentana(JPanel panel, String titulo) {
        // Crear una nueva ventana (JFrame) para representar el JPanel
        JFrame ventanaPanel = new JFrame(titulo);

        // Configurar la ventana
        ventanaPanel.setSize(500, 300); // Ajusta el tamaño según tus necesidades
        ventanaPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Agregar el JPanel a la ventana
        ventanaPanel.add(panel);

        // Hacer visible la ventana
        ventanaPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCompanyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCompanyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCompanyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCompanyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCompanyas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarComp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCodigoComp;
    private javax.swing.JTextField txtDirSedeCentral;
    private javax.swing.JTextField txtMunicipioSedeCentral;
    private javax.swing.JTextField txtNombreComp;
    private javax.swing.JTextField txtPrefijoComp;
    private javax.swing.JTextField txtTlfInfoAeropuerto;
    private javax.swing.JTextField txtTlfInfoPasajeros;
    // End of variables declaration//GEN-END:variables

    
}
